hostname: "ncar-im-15th-virginia"
address: "192.168.1.101"
controller_address: "192.168.1.42"
sensors:
  - lidar_type: "VelodyneVLP16"
    gps:
      latitude: 39.0
      longitude: -119.0
    address: "192.168.1.202"
    port: 2330
    frame_id: "lidar_0"
    namespace: "lidar_0"
  - lidar_type: "VelodyneVLP16"
    gps:
      latitude: 39.0
      longitude: -119.0
    address: "192.168.1.222"
    port: 2340
    frame_id: "lidar_1"
    namespace: "lidar_1"
