hostname: "virginia_college_host"
address: "172.20.133.22"
controller_address: "192.168.1.42"
sensors:
  - lidar_type: "VelodyneVLP32C"
    gps:
      latitude: 39.540503
      longitude: -119.817272
    address: "172.20.133.30"
    port: 2340
    frame_id: "virginia_college_se"
    namespace: "virginia_college_se"
    running: true
  - lidar_type: "VelodyneVLP32C"
    gps:
      latitude: 39.540708
      longitude: -119.816908
    address: "172.20.133.31"
    port: 2350
    frame_id: "virginia_college_ne"
    namespace: "virginia_college_ne"
    running: true
