hostname: "virginia_15th_host"
address: "172.20.133.2"
controller_address: "192.168.1.42"
sensors:
  - lidar_type: "VelodyneVLP32C"
    gps:
      latitude: 39.0
      longitude: -119.0
    address: "172.20.133.10"
    port: 2340
    frame_id: "virginia_15th_se"
    namespace: "virginia_15th_se"
  - lidar_type: "VelodyneVLP32C"
    gps:
      latitude: 39.0
      longitude: -119.0
    address: "172.20.133.11"
    port: 2350
    frame_id: "virginia_15th_nw"
    namespace: "virginia_15th_nw"
